[build]
  publish = "public"
  functions = "netlify/functions"

[functions."generate-saml-assertion"]
  runtime = "python3.11"

[[redirects]]
  from = "/generate-saml-assertion"
  to = "/.netlify/functions/generate-saml-assertion"
  status = 200
